# Generated by Django 4.2.24 on 2025-09-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='email_core.emailaccount'),
        ),
    ]
