# Generated by Django 4.2.24 on 2025-09-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_core', '0002_alter_email_email_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='QKDKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ksid', models.CharField(help_text='Key Stream ID', max_length=255)),
                ('key_data', models.BinaryField(help_text='Encrypted quantum key material')),
                ('key_size_bits', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('error', 'Error')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_usage', models.IntegerField(default=1, help_text='Maximum number of times this key can be used')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QKDKeyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='Base URL for Key Manager REST API')),
                ('api_version', models.CharField(default='v1', max_length=10)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('default_key_size', models.IntegerField(default=256, help_text='Default key size in bits')),
                ('max_key_lifetime', models.IntegerField(default=3600, help_text='Maximum key lifetime in seconds')),
                ('is_simulated', models.BooleanField(default=True, help_text='Whether this is a simulated KM for testing')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QKDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('error', 'Error')], default='initializing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('key_derivation_rounds', models.IntegerField(default=10000)),
                ('key_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_core.qkdkeymanager')),
                ('shared_keys', models.ManyToManyField(blank=True, to='email_core.qkdkey')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sender_email', 'recipient_email', 'status')},
            },
        ),
        migrations.CreateModel(
            name='QuantumEncryptedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('key_derivation_salt', models.BinaryField(max_length=32)),
                ('initialization_vector', models.BinaryField(max_length=16)),
                ('encrypted_subject', models.BinaryField(blank=True, null=True)),
                ('encrypted_body_text', models.BinaryField(blank=True, null=True)),
                ('encrypted_body_html', models.BinaryField(blank=True, null=True)),
                ('quantum_security_level', models.IntegerField(default=256, help_text='Security level in bits')),
                ('key_consumption_timestamp', models.DateTimeField()),
                ('forward_secrecy_enabled', models.BooleanField(default=True)),
                ('integrity_hash', models.CharField(help_text='SHA-256 hash for integrity verification', max_length=64)),
                ('quantum_signature', models.BinaryField(blank=True, help_text='Quantum authentication signature', null=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantum_data', to='email_core.email')),
                ('encryption_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_core.qkdkey')),
                ('qkd_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_emails', to='email_core.qkdsession')),
            ],
            options={
                'ordering': ['-key_consumption_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='qkdkey',
            name='key_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='email_core.qkdkeymanager'),
        ),
        migrations.CreateModel(
            name='ExternalEmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(choices=[('gmail', 'Gmail'), ('yahoo', 'Yahoo Mail'), ('outlook', 'Outlook.com'), ('custom_imap', 'Custom IMAP'), ('custom_smtp', 'Custom SMTP')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField()),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
                ('smtp_use_ssl', models.BooleanField(default=True)),
                ('smtp_use_tls', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('oauth2_token', models.TextField(blank=True, null=True)),
                ('oauth2_refresh_token', models.TextField(blank=True, null=True)),
                ('oauth2_expires_at', models.DateTimeField(blank=True, null=True)),
                ('qkd_enabled', models.BooleanField(default=True, help_text='Enable quantum encryption for this provider')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_key_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_core.qkdkeymanager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_email_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='qkdkey',
            index=models.Index(fields=['ksid', 'status'], name='email_core__ksid_3cc0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='qkdkey',
            index=models.Index(fields=['sender_email', 'recipient_email'], name='email_core__sender__2c92ab_idx'),
        ),
        migrations.AddIndex(
            model_name='qkdkey',
            index=models.Index(fields=['expires_at'], name='email_core__expires_350420_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalemailprovider',
            unique_together={('user', 'email_address')},
        ),
    ]
