# Generated by Django 4.2.24 on 2025-09-25 06:21

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('email_core', '0003_qkdkey_qkdkeymanager_qkdsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealQuantumEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                
                # Encrypted content stored as JSON strings
                ('encrypted_subject', models.TextField(help_text='JSON string containing encrypted subject')),
                ('encrypted_body_text', models.TextField(help_text='JSON string containing encrypted body text')),
                ('encrypted_body_html', models.TextField(blank=True, null=True, help_text='JSON string containing encrypted HTML body')),
                
                # Quantum metadata
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('quantum_key_id', models.CharField(max_length=255, help_text='ID of quantum key used')),
                ('quantum_security_level', models.FloatField(default=99.9, help_text='Quantum security level')),
                ('quantum_envelope', models.TextField(help_text='JSON string containing quantum envelope data')),
                
                # Status and timestamps
                ('status', models.CharField(
                    choices=[
                        ('encrypted', 'Encrypted'),
                        ('sent', 'Sent'),
                        ('delivered', 'Delivered'),
                        ('decrypted', 'Decrypted'),
                        ('error', 'Error')
                    ],
                    default='encrypted',
                    max_length=20
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('decrypted_at', models.DateTimeField(blank=True, null=True)),
                
                # Foreign keys
                ('sender_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sent_quantum_emails',
                    to=settings.AUTH_USER_MODEL
                )),
                ('key_manager', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='quantum_emails',
                    to='email_core.qkdkeymanager'
                )),
                ('regular_email', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='real_quantum_data',
                    to='email_core.email'
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
