# Generated by Django 4.2.24 on 2025-09-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_core', '0004_auto_20250925_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Domain name (e.g., localhost, example.com)', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the domain', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the domain')),
                ('is_active', models.BooleanField(default=True, help_text='Whether users can register with this domain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain_name'],
            },
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='full_name',
            field=models.CharField(default='User', help_text='Full name of the user', max_length=255),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Last successful login', null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='password_hash',
            field=models.CharField(default='', help_text='Hashed password', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='quota_mb',
            field=models.IntegerField(default=1000, help_text='Mailbox quota in MB'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='allowed_domain',
            field=models.ForeignKey(blank=True, help_text='Domain this account belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='email_core.alloweddomain'),
        ),
    ]
